Bike/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Users.urls')),
    path('Products/', include('Products.urls')),
    path('Records/', include('Records.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = 'Products'

router = routers.DefaultRouter()
router.register('Bike', views.Bikeview)
router.register('Service', views.Serviceview)
router.register('Accessories', views.Accessoriesview)

urlpatterns = [
    path('api', include(router.urls)),
    #  path('bike/QR',views.Bikeview.QR)
    path('', views.home, name='home'),
    path('product', views.Product_list, name='product_list'),
    path('Rent', views.rent, name='rent_list'),
    path('product/<int:id>', views.Product_detail, name='Product_detail'),
    path('contactus', views.contact, name='contact'),
    path('account', views.account, name='account'),
    path('Cart', views.addtocart, name='cart'),
]

bike_system/urls.py
# from .routers import router
from .views import home
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views
# from django.contrib.auth.views import login
urlpatterns = [
    path('', home.index ),
    # path('rent/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('api-token-auth/', views.obtain_auth_token),
    path('User/', include('Users.urls')),

    path('Products/', include('Products.urls')),
    path('Records/', include('Records.urls')),
    # path('api/', include(router.urls)),
    path('', home.index),
    # path('login/', login, name='login'),

]

shrief/urls.py
# from .routers import router
from .views import home
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views
# from django.contrib.auth.views import login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', home.index),
    # path('rent/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('api-token-auth/', views.obtain_auth_token),
    path('User/', include('Users.urls')),

    # path('Products/', include('Products.urls')),
    path('Records/', include('Records.urls')),
    # path('api/', include(router.urls)),
    # path('', home.index),
    # path('login/', login, name='login'),

    path('', include('Products.urls', namespace='Home')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'Products.views.error_404_view'

templates/base.html
<!--
    1- Signin.
    2- Creat an account.
    3- Contact.
    4- Add to cart.
    5- footer.
-->

{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <!-- bootstrap CDN -->
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
        integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <!-- font awesome CDN -->
    <script src="https://kit.fontawesome.com/9c7f5fa11c.js" crossorigin="anonymous"></script>
    <!-- Custome CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">
    <title>bikes shop</title>
</head>

<body>
    <!-- header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-12 text-center">
                    <h2 class="my-md-3 site-title text-white">Bikes Shop</h2>
                </div>
                <div class="col-md-6 col-12 text-right">
                    <p class="my-md-4 header-links">
                        <a href="{% url 'Home:account' %}" class="px-2">Sign In</a>
                        <a href="{% url 'Home:account' %}" class="px-1">Creat an account</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="container-fluid p-0">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'Home:home' %}">HOME <span
                                    class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Home:product_list' %}">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Home:contact' %}">Contact</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-nav">
                    <li class="nav-item border rounded-circle mx-2 basket-icon">
                        <a href="{% url 'Home:cart' %}"><i class="fas fa-shopping-basket p-2"></i></a>
                    </li>
                </div>
            </nav>
        </div>
    </header>
    <!-- /header -->

    {% block content %}

    {% endblock content %}

    <!-- footer section -->

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>Download Our App</h3>
                    <p>Download App for Android and ios mobile phone.</p>
                    <button type="button" class="btn btn-dark btn-lg tittle-button" style="background: #4f8a8b"> <i
                            class="fab fa-apple"></i> Download</button>
                    <button type="button" class="btn btn-outline-light btn-lg tittle-button"> <i
                            class="fab fa-google-play"></i>
                        Download</button>
                </div>
                <div class="footer-col-4">
                    <h3>Follow Us</h3>
                    <ul>
                        <a href="#">
                            <li>Facebook</li>
                        </a>
                        <a href="#">
                            <li>Twitter</li>
                        </a>
                        <a href="#">
                            <li>Instagram</li>
                        </a>
                    </ul>
                </div>
            </div>
            <hr>
            <p class="copyright">© copyRight 2020 - Medhat Designs</p>
        </div>
    </div>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js"
        integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J"
        crossorigin="anonymous"></script>
    <!-- Custome JavaScript -->
    <script type="text/javascript" src="{% static 'app.js' %}"></script>

    {% block Script %}

    {% endblock Script %}

</body>

</html>