Bike/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Users.urls')),
    path('Products/', include('Products.urls')),
    path('Records/', include('Records.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = 'Products'

router = routers.DefaultRouter()
router.register('Bike', views.Bikeview)
router.register('Service', views.Serviceview)
router.register('Accessories', views.Accessoriesview)

urlpatterns = [
    path('api', include(router.urls)),
    #  path('bike/QR',views.Bikeview.QR)
    path('', views.home, name='home'),
    path('product', views.Product_list, name='product_list'),
    path('Rent', views.rent, name='rent_list'),
    path('product/<int:id>', views.Product_detail, name='Product_detail'),
    path('contactus', views.contact, name='contact'),
    path('account', views.account, name='account'),
    path('Cart', views.addtocart, name='cart'),
]

bike_system/urls.py
# from .routers import router
from .views import home
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views
# from django.contrib.auth.views import login
urlpatterns = [
    path('', home.index ),
    # path('rent/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('api-token-auth/', views.obtain_auth_token),
    path('User/', include('Users.urls')),

    path('Products/', include('Products.urls')),
    path('Records/', include('Records.urls')),
    # path('api/', include(router.urls)),
    path('', home.index),
    # path('login/', login, name='login'),

]

shrief/urls.py
# from .routers import router
from .views import home
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views
# from django.contrib.auth.views import login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', home.index),
    # path('rent/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('api-token-auth/', views.obtain_auth_token),
    path('User/', include('Users.urls')),

    # path('Products/', include('Products.urls')),
    path('Records/', include('Records.urls')),
    # path('api/', include(router.urls)),
    # path('', home.index),
    # path('login/', login, name='login'),

    path('', include('Products.urls', namespace='Home')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'Products.views.error_404_view'

Products/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Bike(models.Model):
    model = models.CharField(max_length=30)  # phoenix
    serial = models.CharField(max_length=30)  # R300
    image = models.ImageField()
    availability = models.BooleanField()  # both rent and sell
    rentability = models.BooleanField()
    availabilityDuration = models.CharField(
        max_length=20)  # available for renting in 3 days
    # used=models.BooleanField()
    description = models.TextField(max_length=300)
    sellPrice = models.IntegerField()
    rentPerDay = models.IntegerField()
    rentPerWeek = models.IntegerField()
    rentPerMonth = models.IntegerField()
    branche = models.CharField(max_length=30)

    def __str__(self):
        return self.model


class BikeImage(models.Model):
    Bike = models.ForeignKey(
        Bike, default=None, on_delete=models.CASCADE, related_name='images')
    images = models.FileField(upload_to='images/')

    def __str__(self):
        return self.Bike.model

    @property
    def image_url(self):
        return "{0}".format(self.images.url)


class Service(models.Model):
    name = models.CharField(max_length=30)
    duration = models.CharField(max_length=30)
    price = models.IntegerField()
    notes = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class accessories(models.Model):
    name = models.CharField(max_length=20)
    sellPrice = models.IntegerField()
    image = models.ImageField()
    availability = models.BooleanField()
    branche = models.CharField(max_length=30)

    def __str__(self):
        return self.name

Products/views.py
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from .models import Bike, Service, accessories, BikeImage
from .serializers import Bikeserializers, Serviceserializers, accessoriesserializers
from rest_framework.decorators import action
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.conf import settings
from django.core.mail import send_mail
#import qrcode
# Create your views here.


class Bikeview(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    queryset = Bike.objects.all()
    serializer_class = Bikeserializers

    #
    # def QR(request):
    #     id=request.POST['id']
    #
    #     #qrcode generator
    #     qr=qrcode.QRCode(version=1,box_size=10,border=5)
    #     data=""+id
    #     qr.add_data(data)
    #     qr.make(fit=True)
    #     img=qr.make_image(fill="black",back_color="white")
    #     url="QR/"+data+".png"
    #     img.save(url)
    #    # img.show()
    #     return HttpResponse(img)

    # img.save("image", format=None)
    # has img


class Serviceview(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = Service.objects.all()
    serializer_class = Serviceserializers


class Accessoriesview(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    queryset = accessories.objects.all()
    serializer_class = accessoriesserializers
    # has img
    # def create(self, request):
    #     # new=models.RentRecords()
    #     # new.customer=models.RentUser(id=1)
    #     # new.bike= models.Bike(id=1)
    #     # new.starts= request.POST['starts']
    #     # new.ends= request.POST['ends']
    #     # new.status= request.POST['status'] #must be post-now
    #     # new.note= request.POST['note']
    #     # new.price= request.POST['price']
    #     # new.save()
    #     return Response('hello')

    # def retrieve(self, request, pk=None):
    #     pass
    #
    # def update(self, request, pk=None):
    #     pass
    #
    # def partial_update(self, request, pk=None):
    #     pass
    #
    # def destroy(self, request, pk=None):
    #     pass


def home(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        find_us = request.POST['find-us']
        news = request.POST['news']
        message = request.POST['message']

        send_mail(name, message,
                  email, [settings.EMAIL_HOST_USER])

    first_products = Bike.objects.all().order_by('id')
    first_products = first_products[:3]

    last_products = Bike.objects.all().order_by('-id')
    last_products = last_products[:6]

    context = {
        'first_products': first_products,
        'last_products': last_products,
    }
    return render(request, 'Products/index.html', context)


def Product_list(request):
    Product_list = Bike.objects.all().order_by('-id')
    service = Service.objects.all().order_by('-id')

    # search_term = ''
    # if 'search' in request.GET:
    #     search_term = request.GET['search']
    #     Product_list = Product_list.filter(model__icontains=search_term)

    paginator = Paginator(Product_list, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'products': page_obj,
        'service': service,
        # 'search_term': search_term,
    }
    return render(request, 'Products/Buy_1.html', context)


def rent(request):
    Rent_list = Bike.objects.filter(rentability=True).order_by('-id')
    service = Service.objects.all().order_by('-id')

    search_term = ''
    if 'search' in request.GET:
        search_term = request.GET['search']
        Rent_list = Rent_list.filter(model__icontains=search_term)

    paginator = Paginator(Rent_list, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'Rent': page_obj,
        'service': service,
        'search_term': search_term,
    }
    return render(request, 'Products/Rent_1.html', context)


def Product_detail(request, id):

    first_products = Bike.objects.all().order_by('id')
    first_products = first_products[:3]

    Product_detail = Bike.objects.get(id=id)
    photos = BikeImage.objects.filter(Bike=Product_detail)
    service = Service.objects.all().order_by('-id')
    context = {
        'product': Product_detail,
        'service': service,
        'photos': photos,
        'first_products': first_products,
    }
    return render(request, 'Products/display_product.html', context)


def contact(request):
    return render(request, 'Products/contact.html')


def account(request):
    return render(request, 'Products/sign-in.html')


def addtocart(request):
    return render(request, 'Products/cart.html')


def error_404_view(request, exception):
    return render(request, 'Products/page404.html')

Products/templates/Products/Rent_1.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Rent</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/--mp--Animated-Service-Box-1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/--mp--Animated-Service-Box.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Features-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-with-Search.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Pretty-Footer.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static '/resources/favicons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static '/resources/favicons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static '/resources/favicons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static '/resources/favicons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static '/resources/favicons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static '/resources/favicons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static '/resources/favicons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static '/resources/favicons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/resources/favicons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" href="{% static '/resources/favicons/favicon-32x32.png' %}" sizes="32x32">
    <!--<link rel="icon" type="image/png" href="{% static '/resources/favicons/favicon-194x194.png' %}" sizes="194x194">-->
    <link rel="icon" type="image/png" href="{% static '/resources/favicons/favicon-96x96.png' %}" sizes="96x96">
    <link rel="icon" type="image/png" href="{% static '/resources/favicons/android-icon-192x192.png' %}"
        sizes="192x192">
    <link rel="icon" type="image/png" href="{% static '/resources/favicons/favicon-16x16.png' %}" sizes="16x16">
    <link rel="manifest" href="{% static '/resources/favicons/manifest.json' %}">
    <link rel="shortcut icon" href="{% static '/resources/favicons/favicon.ico' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="{% static '/resources/favicons/ms-icon-144x144.png' %}">
    <meta name="msapplication-config" content="{% static '/resources/favicons/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
    <style>
        .card-img-top {
            max-height: 200px;
            min-height: 150px;
            object-fit: cover;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-md navigation-clean-search" data-aos="slide-down">
        <div class="container"><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span
                    class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button><img
                src="{% static 'assets/img/logo.png' %}" width="60" height="60">
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'Home:home' %}">Home</a>
                    </li>
                    <li class="nav-item" role="presentation"><a class="nav-link"
                            href="{% url 'Home:product_list' %}">Buy</a></li>
                    <li class="nav-item" role="presentation"></li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                        name='search' value="{{search_term}}">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            {% for rent in Rent %}
            {% if rent.rentability %}
            <div class="col-md-4 col-sm-6 col-12">
                <div class="card shadow-lg h-70" data-bs-hover-animate="bounce"
                    style="margin: 20px;padding: 20px;background-size: auto;background-color: rgb(255,255,255);color: rgb(33,37,41);">
                    <div class="inner">
                        <img class="card-img-top w-100 d-block" src="{{rent.image.url}}">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{rent.model}}</h4>
                        <p class="card-text">{{rent.description|truncatechars:50}}</p>

                        <!-- {% if rent.availability %} -->
                        <a href="{% url 'Home:Product_detail' rent.id %}" class="btn btn-outline-primary"
                            type="button">RENT NOW</a>
                        <!-- {% else %} -->
                        <!-- <button class="btn btn-lg btn-primary" type="button" disabled>RENT NOW</button> -->
                        <!-- {% endif %} -->
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% if Rent.has_other_pages %}
    <nav
        class="text-center border rounded-0 border-white shadow d-flex d-sm-flex d-md-flex d-lg-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center">
        <ul class="pagination">
            {% if Rent.has_previous %}
            <li
                class="page-item text-center border rounded-circle d-lg-flex justify-content-lg-center align-items-lg-center">
                <a class="page-link" href="?page={{Rent.previous_page_number}}" aria-label="Previous"><span
                        aria-hidden="true">«</span></a></li>
            {% endif %}
            {% for i in Rent.paginator.page_range %}
            <li class="page-item border rounded-circle"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endfor %}
            {% if Rent.has_next %}
            <li class="page-item border rounded-circle"><a class="page-link" href="?page={{Rent.next_page_number}}"
                    aria-label="Next"><span aria-hidden="true">»</span></a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    <br>
    <br>
    <section>
        <br>
        <h2 class="text-center">Service<br></h2>
        <div class="container">
            <div class="row">
                {% for i in service %}

                <div class="col-sm-12 col-md-4">
                    <div class="serviceBox">
                        <div class="service-icon"><span><i class="fa fa-bicycle"></i></span></div>
                        <h1 class="titleBlurb">{{i.name}}</h1>
                        <p>{{i.notes}}</p>
                    </div>
                </div>

                {% endfor %}
            </div>
        </div>
    </section>
    <footer>
        <div class="row">
            <div class="col-sm-6 col-md-4 footer-navigation">
                <h3><a href="{% url 'Home:home' %}">Company<span>logo </span></a></h3>
                <p class="links"><a href="{% url 'Home:home' %}">Home</a><strong> · </strong><a>Blog</a><strong>
                        · </strong><a href="https://github.com/orgs/Pharon-sTimeGate/dashboard">About</a><strong> ·
                    </strong><a href="https://github.com/orgs/Pharon-sTimeGate/dashboard">Contact</a></p>
                <p class="company-name">Company Name © 2020 </p>
            </div>
            <div class="col-sm-6 col-md-4 footer-contacts">
                <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                    <p><span class="new-line-span">21 Revolution Street</span> Cairo, Egypt</p>
                </div>
                <div><i class="fa fa-phone footer-contacts-icon"></i>
                    <p class="footer-center-info email text-left"> +201010748400</p>
                </div>
                <div><i class="fa fa-envelope footer-contacts-icon"></i>
                    <p> <a href="#" target="_blank">tefa2436@gmail.com</a></p>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-md-4 footer-about">
                <h4>About the company</h4>
                <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor
                    lacus vehicula sit amet. </p>
                <div class="social-links social-icons"><a href="https://www.facebook.com/sherif4cycle/"><i
                            class="fa fa-facebook"></i></a><a><i class="fa fa-twitter"></i></a><a><i
                            class="fa fa-linkedin"></i></a><a
                        href="https://github.com/orgs/Pharon-sTimeGate/dashboard"><i class="fa fa-github"></i></a></div>
            </div>
        </div>
    </footer>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/bs-init.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.js"></script>
</body>

</html>

Products/templates/Products/buy.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
    content="Shereif is store service bicycle and offer spare parts one of the best of the field.">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'vendors/css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'vendors/css/grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'vendors/css/ionicons.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'vendors/css/animate.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'resources/css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'resources/css/queries.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,300italic' rel='stylesheet' type='text/css'>

  <title>BUY</title>

</head>
<header>
  <script type="text/javascript" src="{% static 'bootstrap.min.js' %}"></script>

  <nav class="navbar  fixed-top navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
      <img src="{% static 'resources/img/logo.png' %}" width="60" height="60" class="d-inline-block align-top" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Home:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Home:rent_list' %}">Rent <span class="sr-only">(current)</span></a>
        </li>



      </ul>
    </div>
  </nav>
</header>



<body>

  <h2>CHOOSE YOUR OWN BIKE KNOW!</h2>



  <div id="mySidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>


    <h4>OUR SERVICES!</h4>
    <dl>
      <dt>service name</dt>
      <dd>- discription<a href="tel:555-555-5555">phone number</a></dd>
      <dt>service name</dt>
      <dd>- discription<a href="tel:555-555-5555"> phone number</a></dd>
    </dl>
    <dl>
      <dt>service name</dt>
      <dd>- discription<a href="tel:555-555-5555">phone number</a></dd>
      <dt>service name</dt>
      <dd>- discription<a href="tel:555-555-5555"> phone number</a></dd>
    </dl>
    <dl>
      <dt>service name</dt>
      <dd>- discription<a href="tel:555-555-5555">phone number</a></dd>
      <dt>service name</dt>
      <dd>- discription<a href="tel:555-555-5555"> phone number</a></dd>
    </dl>
    <dl>
      <dt>service name</dt>
      <dd>- discription<a href="tel:555-555-5555">phone number</a></dd>
      <dt>service name</dt>
      <dd>- discription<a href="tel:555-555-5555"> phone number</a></dd>
    </dl>
  </div>











  <div class="main">
    <button class="openbtn" onclick="openNav()">&#9776;CHECK OUR SERVICES</button>
    <div class="container">
      <div class="row">

        {% for product in products %}

        <div class="col-sm-3">
          <div class="card mx-2" style="width: 12rem;">
            <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">{{product.sellPrice}}</h5>
              <p class="card-text">{{product.description|truncatewords:5}}</p>
              <a href="{% url 'Products:Product_detail' product.id %}" class="btn btn-ghost">BUY NOW</a>
            </div>
          </div>
        </div>

        {% endfor %}



      </div>



      {% if products.has_other_pages %}
      <div class="pag">
        <ul class="pagination">

          {% if products.has_previous %}
          <li><a href="?page={{products.previous_page_number}}" class="prev">
              < Prev</a>
          </li>
          {% endif %}

          {% for i in products.paginator.page_range %}

          {% ifequal products.number i %}
          <li class="pageNumber active"><a href="?page={{i}}">{{i}}</a></li>
          {% else %}
          <li class="pageNumber"><a href="?page={{i}}">{{i}}</a></li>
          {% endifequal %}
          {% endfor %}

          {% if products.has_next %}
          <li><a href="?page={{products.next_page_number}}" class="next">
              Next ></a>
          </li>
          {% endif %}

        </ul>
      </div>
      {% endif %}






    </div>



    <footer>
      <div class="row">
        <div class="col span-1-of-2">
          <ul class="footer-nav">
            <li><a href="#">About us</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Press</a></li>
            <li><a href="#">iOS App</a></li>
            <li><a href="#">Android App</a></li>
          </ul>
        </div>
        <div class="col span-1-of-2">
          <ul class="social-links">
            <li><a href="#"><i class="ion-social-facebook"></i></a></li>
            <li><a href="#"><i class="ion-social-twitter"></i></a></li>
            <li><a href="#"><i class="ion-social-googleplus"></i></a></li>
            <li><a href="#"><i class="ion-social-instagram"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <p>
          Copyright &copy; 2020 by shereif store. All rights reserved.
        </p>
      </div>
    </footer>







  </div>














  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="//cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
  <script src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="//cdn.jsdelivr.net/selectivizr/1.0.3b/selectivizr.min.js"></script>
  <script src="{% static 'vendors/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'resources/js/script.js' %}"></script>

  <script>
    (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-61026110-2', 'auto');
    ga('send', 'pageview');

  </script>


  <script>/* Set the width of the sidebar to 250px and the left margin of the page content to 250px */
    function openNav() {
      document.getElementById("mySidebar").style.width = "150px";
      document.getElementById("main").style.marginLeft = "350px";
    }

    /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
    function closeNav() {
      document.getElementById("mySidebar").style.width = "0";
      document.getElementById("main").style.marginLeft = "0";
    }</script>

  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript">
    $('.pagination .pageNumber a').on("click", function () {
      if (!$(this).parent().hasClass('active')) {
        $(".pagination .pageNumber.active").removeClass("active");
        $(this).parent().addClass("active");
      }
    })
    $(document).ready(function () {
      $('.next').click(function () {
        $('.pagination').find('.pageNumber.active').next().
          addClass('active');
        $('.pagination').find('.pageNumber.active').prev().
          removeClass('active');
      })
      $('.prev').click(function () {
        $('.pagination').find('.pageNumber.active').prev().
          addClass('active');
        $('.pagination').find('.pageNumber.active').next().
          removeClass('active');
      })
    })
  </script>

</body>

</html>

Products/templates/Products/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="small-container card-page">
  <table>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Subtotal</th>
    </tr>
    <tr>
      <td>
        <div class="cart-info">
          <img src="{% static 'images/bike12.jfif' %}" alt="">
          <div class="">
            <p>High Quality Bike</p>
            <small>Price: $60.00</small>
            <br>
            <a href="#">Remove</a>
          </div>
        </div>
      </td>
      <td> <input type="number" value="1"> </td>
      <td>$60.00</td>
    </tr>

  </table>

  <div class="total-price">
    <table>
      <tr>
        <td>Subtotal</td>
        <td>$160.00</td>
      </tr>
      <tr>
        <td>Tax</td>
        <td>$40.00</td>
      </tr>
      <tr>
        <td>Total</td>
        <td>$200.00</td>
      </tr>
    </table>
  </div>


</div>

{% endblock content %}